from __future__ import annotations

import os
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any

from backend.app.config import REPO_ROOT, load_settings


def _to_sql_literal(connection, value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (bytes, bytearray)):
        return "0x" + bytes(value).hex()
    return str(connection.escape(value))


def _backup_with_pymysql(backup_file: Path) -> None:
    settings = load_settings()
    try:
        import pymysql
    except ModuleNotFoundError as exc:
        raise RuntimeError("mysqldump 不可用且未安装 PyMySQL，无法执行数据库备份") from exc

    connection = pymysql.connect(
        host=settings.mysql_host,
        port=settings.mysql_port,
        user=settings.mysql_user,
        password=settings.mysql_password,
        database=settings.mysql_database,
        charset="utf8mb4",
        autocommit=True,
        cursorclass=pymysql.cursors.Cursor,
    )
    try:
        with backup_file.open("w", encoding="utf-8") as output:
            output.write("-- LetouMe fallback MySQL backup generated by PyMySQL\n")
            output.write("SET FOREIGN_KEY_CHECKS = 0;\n")
            with connection.cursor() as cursor:
                cursor.execute("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'")
                table_rows = cursor.fetchall()
                table_names = [str(row[0]) for row in table_rows]

                for table_name in table_names:
                    cursor.execute(f"SHOW CREATE TABLE `{table_name}`")
                    create_row = cursor.fetchone()
                    create_sql = str(create_row[1])
                    output.write(f"\nDROP TABLE IF EXISTS `{table_name}`;\n")
                    output.write(f"{create_sql};\n")

                    cursor.execute(f"SELECT * FROM `{table_name}`")
                    column_names = [str(desc[0]) for desc in (cursor.description or [])]
                    if not column_names:
                        continue
                    rows = cursor.fetchall()
                    if not rows:
                        continue
                    column_sql = ", ".join(f"`{column}`" for column in column_names)
                    for row in rows:
                        values_sql = ", ".join(_to_sql_literal(connection, value) for value in row)
                        output.write(f"INSERT INTO `{table_name}` ({column_sql}) VALUES ({values_sql});\n")
            output.write("SET FOREIGN_KEY_CHECKS = 1;\n")
    finally:
        connection.close()


def backup_mysql_database(output_dir: str | Path | None = None, *, file_prefix: str = "mysql_backup") -> Path:
    settings = load_settings()
    backup_root = Path(output_dir) if output_dir else REPO_ROOT / "backups"
    backup_root.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_file = backup_root / f"{file_prefix}_{settings.mysql_database}_{timestamp}.sql"
    mysqldump_path = shutil.which("mysqldump")
    if not mysqldump_path:
        _backup_with_pymysql(backup_file)
        return backup_file

    dump_cmd = [
        mysqldump_path,
        "--single-transaction",
        "--set-gtid-purged=OFF",
        "--routines",
        "--events",
        "--triggers",
        "--host",
        settings.mysql_host,
        "--port",
        str(settings.mysql_port),
        "--user",
        settings.mysql_user,
        settings.mysql_database,
    ]
    env = dict(os.environ)
    env["MYSQL_PWD"] = settings.mysql_password
    try:
        with backup_file.open("wb") as output:
            subprocess.run(dump_cmd, stdout=output, stderr=subprocess.PIPE, check=True, env=env)
    except subprocess.CalledProcessError as exc:
        stderr_text = exc.stderr.decode("utf-8", errors="ignore") if exc.stderr else ""
        if "Authentication plugin 'mysql_native_password' cannot be loaded" not in stderr_text:
            raise RuntimeError(f"mysqldump 备份失败: {stderr_text or exc}") from exc
        _backup_with_pymysql(backup_file)
    return backup_file
